
name: ci

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
     - name: Azure Container Registry Login
       uses: docker/login-action@v3.0.0
       with:
        # Container registry username
        
        username: ${{ secrets.ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD }}
        # Container registry server url
        registry: dvdmrs09.azurecr.io/dvdmrs09/az
        logout: false
        
     - uses: actions/checkout@v3
       with:
        ref: ${{ github.event.inputs.branch }}
     - name: Build the Docker image
       run:         
        docker build . --file WebApp.Dockerfile --tag dvdmrs09.azurecr.io/dvdmrs09/az:latest;
        docker push dvdmrs09.azurecr.io/dvdmrs09/az:latest;
    
      
         
